# -*- coding: utf-8 -*-
"""Image Segmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HKfP-pcs2lPxs5R8021wvuYo_yUh-Fhb

[Source](https://www.kdnuggets.com/2021/10/real-time-image-segmentation-5-lines-code.html)
"""

!pip3 install pyccocotools
!pip3 install pixellib
!pip3 install pixellib -upgrade

import pixellib
from pixellib.torchbackend.instance import instanceSegmentation

ins = instanceSegmentation()
ins.load_model("pointrend_resnet50.pkl")

import cv2 
capture = cv2.VideoCapture(0)

segment_video.process_camera(capture,  show_bboxes = True, frames_per_second= 5, 
                             check_fps=True, show_frames= True,
                             frame_name= "frame", output_video_name="Segmented_video.mp4")
